### ISSUE TITLE
Monster specials

### ISSUE THREAD

**Issue by Deedasmi** [CIS-580-Fall-2015/MonsterArena#1]

**Comment by nicjohnson145** [comment]
double life: after death, instantly respawns at door it came from

**Comment by nicjohnson145** [comment]
change to deal double damage
change to take half damage

**Comment by nicjohnson145** [comment]
chance*

**Comment by Deedasmi** [comment]
Healing (self and ally)
Taunts
Drop aggro

**Comment by npkellogg** [comment]
Magic attack (ignores hero defense)
Poison/bleed (damage over time)
Buff own/allies' attack/speed/defense

**Comment by Deedasmi** [comment]
Crit, heal, taunt, and dodge implemented.
