### ISSUE TITLE
Entity animations caused problems

### ISSUE THREAD

**Issue by Deedasmi** [CIS-580-Fall-2015/MonsterArena#12]
Had to revert the changes made to monster.js today. Object style didn't work at all (can't set object properties inside object creation). Check out Boss.js and Bosser.js. Will that format work instead?

**Comment by ChristianJHughes** [comment]
My apologies -- the "this.property = propertyValue" notation was incorrect. The correct implementation should be "property: propertyValue" to create properties within the object. You can deffintily set object properties within object creation. See http://www.w3schools.com/js/js_objects.asp.

I will modify the previous version of monster.js to ensure proper syntax, then commit that to master.

**Comment by Deedasmi** [comment]
I wrote a script that fixed all those syntax errors already (8 lines of python fixed every one of them!). Setting the img source still threw errors, as well as trying to set the animation frames. Will simply returning the frames like I do in Boss.js work? It's quite a bit cleaner too. Then we can simply grab the animation object for the direction the creature is facing.

**Comment by ChristianJHughes** [comment]
Yeah, I see what you mean. I'm not sure what the syntax is, though I'm sure it's possible. I'm fine with just modifying the individual monster.js files and exporting their animations; there is other animation code that was lost in the branch revert (which I will modify to accommodate the new export method). Are your edits to Monster.js up to date?

**Comment by Deedasmi** [comment]
Resolved. Good work @ChristianJHughes
