### ISSUE TITLE
Movement wrong

### ISSUE THREAD

**Issue by Deedasmi** [CIS-580-Fall-2015/MonsterArena#14]
Monsters stop moving if inside the X range even if not in right Y position. See current master build for details. 
1. ShopManager.addGold(150000)
2. Purchase door upgrades (all)
3. Spawn monsters

**Comment by dbarnes3** [comment]
I'll work on this tomorrow, it was my plan to test and fix it all after my
1150 final

**Comment by dbarnes3** [comment]
I am working on fixing the X/Y poositioning right now
