### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by idspeer** [CIS-580-Fall-2015/MonsterArena#5]
Create a splash on game entry. Have options to view description and start game.

**Comment by idspeer** [comment]
Splash screen is working with a placeholder image.

**Comment by Deedasmi** [comment]
Temporarily disabled for debugging purposes. Stupid Javascript scope. Tagging Nic to re-implement once we're ready to go.

**Comment by idspeer** [comment]
Splash screen is working with image Nate provided.
