### ISSUE TITLE
Meeting!

### ISSUE THREAD

**Issue by nicjohnson145** [CIS-580-Fall-2015/MonsterArena#7]
Meeting time is Sunday (December 15) @ 2 in Nichols 122.

**Comment by idspeer** [comment]
Richard, did you get my email I sent on Friday regarding meeting times?

**Comment by Deedasmi** [comment]
Yes, and that's fine. We'll try to meet again Monday night probably. Time will likely be discussed at the meeting tomorrow.

**Comment by Deedasmi** [comment]
Monday at 7 p.m. for the next meeting!

**Comment by kbrown2193** [comment]
Won't make it to the meeting tonight, but will push some updates later tonight

**Comment by nicjohnson145** [comment]
I'm assuming it'll be stuff about the sound engine? Spawn sounds and what not?

**Comment by kbrown2193** [comment]
Yeah, some spawn sound functionality, update some sound files, multiple fx.

**Comment by nicjohnson145** [comment]
Tuesday (12/15) @ 5:00 pm. Still in Nichols 122

**Comment by idspeer** [comment]
I may be a late.

**Comment by dbarnes3** [comment]
if i am late today, its becuase I am lost on fixing issue in game  in Nichols 126 (where i am stationed right now)

**Comment by Deedasmi** [comment]
We should meet once more tomorrow to do code cleanup and figure out the presentation . I'm available all day.

**Comment by idspeer** [comment]
I just got off work, are you all still at nichols?

**Comment by Deedasmi** [comment]
No sir. I've updated the TODO section of the readme with what is left.

**Comment by dbarnes3** [comment]
There are 2 of us still in 126, if you want any updates

**Comment by nicjohnson145** [comment]
Would 2 pm in Nichols (122 ? 126) work for everyone?

**Comment by idspeer** [comment]
My last final today is at 6. I'll head to Nichols directly after.

**Comment by ChristianJHughes** [comment]
I can be there at 8 PM tonight. Will you guys be there. Regardless, we should absolutely meet tomorrow prior to our presentation to prepare.

**Comment by dbarnes3** [comment]
When are we meeting today

**Comment by ChristianJHughes** [comment]
We're meeting in Nichols at 3 PM today!

**Comment by kbrown2193** [comment]
Will be there ~ 3:10

**Comment by Deedasmi** [comment]
200/200 gents, good job.
