### ISSUE TITLE
Arena poorly scaled

### ISSUE THREAD

**Issue by Deedasmi** [CIS-580-Fall-2015/MonsterArena#9]
1. Pull master
2. Open Index

Can we get the arena to be more square-like? I like the size of our UIs, scaling the Arena up to a similar size would be fine by me.

**Comment by idspeer** [comment]
I'll crop the original image to better fit what we have.

**Comment by Deedasmi** [comment]
Thanks mate. Just add 

`Closes #9`

To the commit that fixes it, it'll auto-close this ticket.

**Comment by Deedasmi** [comment]
Resolved
